### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by dovy** [divinity76/haydayshit#1]

**Comment by divinity76** [comment]
it mostly doesn't work, it's remains of my attempts at cheating in the game, 
i had some success, but most of it went nowhere, also i quit playing that game years ago  (but girlfriend still plays it!)

notably, it's possible to fool the game into thinking you have 2000+ facebook friends that play the game, which gives you in-game awards.

**Comment by dovy** [comment]
Umm, how can I do that? Haha.

**Comment by divinity76** [comment]
on a facebook Hay Day fan page you can scrape players that play the game (there's a list of people who "liked this page", and i guess almost everyone who liked the page have also played the game, makes sense right?), once you have a list of facebook users who play the game, it's possible to perform a ["Man-in-the-middle attack"](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) (aka "MITM") on the Facebook Graph API used by Hay Day to check your facebook friend list, and make it return a fake list, once Hay Day sees the fake list, it will give you all the in-game rewards for having facebook-friends that play the game, and crucially, when you turn off the MITM and go back to your real facebook list, you will not lose the rewards, so it only needs to be done 1 time.

i used [Fiddler Proxy](https://en.wikipedia.org/wiki/Fiddler_(software)) to do the MITM.

**Comment by divinity76** [comment]
https://github.com/divinity76/haydayshit/blob/master/2000_GraphApiHayDayPlayerResponse.json is a fake friendlist with ~2000 Hay Day players, and https://github.com/divinity76/haydayshit/blob/master/fakefriends.js is the Fiddler-proxy code to inject the fake list when Hay Day is asking for it,

but the the friendlist is from 2014, it's quite some time ago, so it's possible that the format/syntax/url has changed, idk

**Comment by divinity76** [comment]
another thing to keep in mind, the default fake certificate is not accepted by some phones (not my phone at least), i had to use a different certificate-generator to get iOS to accept it, you can read about that here https://www.telerik.com/blogs/the-certenroll-certificate-generator
